#!/bin/sh

file=$1
for width in 008 016 032 064 128 256; do
	for order in '' '-m'; do
		../hex2png \
			-w $width \
			$order \
			-s 32768 \
			$file \
		| convert - \
			$file.$width.$order.png
	done
done
